### ISSUE TITLE
APK Download

### ISSUE THREAD

**Issue by IzzySoft** [Breta01/docus#12]
Would you mind providing the (signed) APK for download (ideally attached to its corresponding [release](https://github.com/Breta01/docus/releases)) so users could give it a try? Would also be interesting to know the app's requirements (does it e.g. depend on OpenCV already being available on-device). Thanks!

**Comment by Breta01** [comment]
Hi, adding APK to release section is good idea. Right now the app is also in review process for Google Play. I will provide you with link once it is published (hopefully during following week).

There are no other requirements, the APK should be self-sufficient. The app currently supports only Android 5.0+

**Comment by IzzySoft** [comment]
That's cool – and thanks for the fast response! From your description, this sounds like the app I'm after personally :smiley:

Additionally, once you've made the APK available at the releases tab, I offer you to include it with [my F-Droid repo](https://apt.izzysoft.de/fdroid) (which is quite popular if I may say so – just do a web search for "izzyondroid repo"). Updates will be fetched within 24h of your creating a new tag with an APK attached to it.

I'd further recommend you establishing [Fastlane file structure](https://gitlab.com/snippets/1895688) in your repo: you can use that for deployments to Play Store, and my updater would pick the per-release changelogs from that (to be shown right next to the description on my website as well as in the F-Droid app). That's optional of course, but would be nice to have :wink: If at one point you decide to apply for the [F-Droid main repo](https://f-droid.org/), summary/description and screenshots would be picked up from Fastlane as well.

**Comment by Breta01** [comment]
Hi,
the application is now available on Google Play <https://play.google.com/store/apps/details?id=com.bretahajek.docus>. There are might still be some issues with the application. There are many updates I would like to do, but right now I am focusing on different project.

Thanks for suggesting Fastlane file structure. I will definitely try to implement that.

**Comment by IzzySoft** [comment]
Thanks! So when will the APK be available here (e.g. attached to releases)? I don't have any GApps on my devices (by choice) and thus do not use Play Store. Many of us "privacy folks" have a similar setup. And many more have it not-by-choice (think China, think Huawei).

Would be great if you could provide the APK here for all of us. My above offer stands, to make it easier for the users to *not* miss an update.

**Comment by IzzySoft** [comment]
<img src="https://gitlab.com/IzzyOnDroid/repo/-/raw/master/assets/IzzyOnDroid.png" width="220" align="middle"> :question: ([source](https://gitlab.com/IzzyOnDroid/repo#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it)) :smiley:

**Comment by IzzySoft** [comment]
@Breta01 any chance to have the APK available here? I'd really like to give it a try, but without the APK I cannot. As I wrote, I don't use Play Store (don't even have it installed on my devices).

**Comment by Breta01** [comment]
Yes I will provide the apk here as soon as possible. I am bit busy right now. I hope to have it here by the end of this week.

**Comment by IzzySoft** [comment]
First things first of course! Thanks for your response! I'll be patient then and look forward to the weekend :smiley: All the best!

**Comment by Breta01** [comment]
Good news! I added the APK file to the release. Keep in mind that it is still more or less beta version. I also look into Fastlane and it's file format. It looks pretty cool. I run the basic setup and I am thinking about using it for automating release process.

I am closing this issue for now. Let me know if there are any issues. @IzzySoft

**Comment by IzzySoft** [comment]
> I added the APK file to the release.

Thanks!!! Ui, it's quite big… I was hoping it would fit into the 30M limit of my repo :cry: Looking inside: could you compile an APK without the x86/x86_64 stuff (i.e. a plain ARM one) and attach that as well (like, `docus-release-arm.apk`, renaming the other to e.g. `docus-release-multiarch.apk` so they could be easily kept apart)? I just did a quick test (unzipping, removing the x86* dirs from `lib/`, zipping the remains) – size is down to about 12M, so I could even keep 2 versions within the 30M.

> Fastlane … I am thinking about using it for automating release process.

That's what it's intended for – great you like it! If you include the per-release changelogs with that, my updater would pull them along (so they are shown inside the F-Droid app as well as on the WebIf).

**Comment by Breta01** [comment]
@IzzySoft 
Yes, I used app bundle for uploading to Google Play. I added the ARM only apk

**Comment by IzzySoft** [comment]
Great, thanks a lot! Your app will [show up here](https://apt.izzysoft.de/fdroid/index/apk/com.bretahajek.docus) in about two hours (with the next sync); be welcome to use above badge to point there then from your Readme :smiley:

Please keep the naming schema (my updater looks for `*arm.apk` at tags now). And it will pick the per-release changelogs from fastlane. If you want something changed on the listing (description, screenshots), just let me know.

----

I've just installed the app on one of my devices (to give it a first look and add some more screenshots) – looks good so far, tagging I find a nice idea! A few questions, though (I will open separate issues for them if you wish):

* are there plans to make use of the flashlight? Currently, if you snap a photo from "directly above" and have no direct lighting from the side, there are a lot of shadows (hands, device, cable if attached)
* I thought OpenCV would imply cropping the image and even applying OCR. Is that planned – or did I get something wrong?
