### ISSUE TITLE
CC license "not recommended" for software

### ISSUE THREAD

**Issue by DC7IA** [Breta01/docus#24]
Hi,

not sure if you are aware:

CC licenses are not recommended for software.

From the FAQ:

> Can I apply a Creative Commons license to software?
> 
> We recommend against using Creative Commons licenses for software. Instead, we strongly encourage you to use one of the very good software licenses which are already available. We recommend considering licenses listed as free by the Free Software Foundation and listed as “open source” by the Open Source Initiative.
> 
> Unlike software-specific licenses, CC licenses do not contain specific terms about the distribution of source code, which is often important to ensuring the free reuse and modifiability of software. Many software licenses also address patent rights, which are important to software but may not be applicable to other copyrightable works. Additionally, our licenses are currently not compatible with the major software licenses, so it would be difficult to integrate CC-licensed work with other free software. Existing software licenses were designed specifically for use with software and offer a similar set of rights to the Creative Commons licenses.
> 
> Version 4.0 of CC’s Attribution-ShareAlike (BY-SA) license is one-way compatible with the GNU General Public License version 3.0 (GPLv3). This compatibility mechanism is designed for situations in which content is integrated into software code in a way that makes it difficult or impossible to distinguish the two. There are special considerations required before using this compatibility mechanism. Read more about it here.
> 
> Also, the CC0 Public Domain Dedication is GPL-compatible and acceptable for software. For details, see the relevant CC0 FAQ entry.
> 
> While we recommend against using a CC license on software itself, CC licenses may be used for software documentation, as well as for separate artistic elements such as game art or music.

https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software

**Comment by Breta01** [comment]
Hi, I admit that the license is not ideal. I will change it to something better. I mainly just want to prevent seeing exact copies of the app appearing in play store.

**Comment by DC7IA** [comment]
The license does not prevent me from doing that. In fact it only requires that I credit you.

![grafik](https://user-images.githubusercontent.com/26351852/125082784-e9c44580-e0c7-11eb-8402-371c5e1215ac.png)

GitHub explains it quite well here: https://github.com/Breta01/docus/blob/master/LICENSE

**Comment by Breta01** [comment]
You right, but I guess no open source license really prevents that. I changed it to GPL3 which is probably more suitable for open source project.
