### ISSUE TITLE
Portuguese short description too long

### ISSUE THREAD

**Issue by IzzySoft** [Breta01/docus#38]
Fastlane `short_description.txt` is limited to 80 chars. Yours for Brasilian Portuguese currently exceeds that and thus is truncated. Could you please fix that before the next release? Thanks!

A possible suggestion (I don't speak the language so I'm not 100% sure) would be:

> Digitalize os seus documentos em papel e organize-os de forma rápida e simples

**Comment by Breta01** [comment]
Hi @IzzySoft, thanks for letting me know. I can't speak Portuguese either, so I just used your suggestion.

**Comment by IzzySoft** [comment]
Thanks! At least it's no longer truncated mid-word then. And native speakers are always welcome to chime in I guess :wink:

Btw: I've used [Deepl](https://www.deepl.com/translator) for this which is known to be quite accurate, so I'm confident we're not "far off" with that.
